# Generated by Django 2.2.3 on 2020-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naive', models.FloatField(max_length=1000)),
                ('nn', models.FloatField(max_length=1000)),
            ],
        ),
    ]
